Introducing GenAI RAD Lab module
GoogleCloudPlatform/rad-lab pull request #159
Opened 2023-08-10 16:17 UTC by guptamukul-google

2023-08-10 19:12 UTC, acolver requested changes
A general suggestion: Can you sort the TF Vars? First by group# then by order#

2023-08-10 20:45 UTC, guptamukul-google commented on modules/gen_ai/variables.tf
> +}
As per my understanding, RAD Lab UI automatically add Owner role to the user who requested the Module creation. Also we would like the user creating the module add other users / groups as Owner.

2023-08-10 20:47 UTC, guptamukul-google commented on modules/gen_ai/variables.tf
> +  description = "Type of VM you would like to spin up. {{UIMeta group=3 order=6 }}"
Exactly! It is difficult to keep a region - machine type mapping therefore not adding machine types in option in UIMeta

2023-08-10 20:53 UTC, guptamukul-google commented on modules/gen_ai/variables.tf
> +  description = "Folder ID where the project should be created. It can be skipped if already setting organization_id. Leave blank if the project should be created directly underneath the Organization
Yes `folder_id ` is `updatesafe` as there won't be any impact on project level and will just move the project from Org to Folder or from Folder to Folder.

2023-08-10 23:02 UTC, acolver commented on modules/gen_ai/README.md
> +````
Looks like it still renders properly.

2023-08-11 00:01 UTC, guptamukul-google commented on modules/gen_ai/README.md
> +````
Yes. 4 backticks works too.

2023-08-11 00:13 UTC, guptamukul-google commented
UIMeta Order is the logical order for RAD Lab UI only but the variables in variables.tf are in alphabetical order for better readability of terraform variables and READMEs which are also built in the same order. 

Also its standardized across all modules.

2023-08-11 00:19 UTC, acolver approved these changes

2023-08-11 17:19 UTC, merged